### ISSUE TITLE
KeyError: 'libraries' in numpy.__config__.blas_opt_info

### ISSUE THREAD

**Issue by thisisjl** [TUT-ARG/DCASE2017-baseline-system#2]
Hi,
I am running `task1.py` on OSX and I get the KeyError in the blas_opt_info when keras is setup. When I run it on linux, I do not get this error.

For reference:
```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/applications/task1.py", line 287, in <module>
    sys.exit(main(sys.argv))
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/applications/task1.py", line 223, in main
    app.system_training()
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/dcase_framework/decorators.py", line 38, in function_wrapper
    to_return = func(*args, **kwargs)
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/dcase_framework/application_core.py", line 1245, in system_training
    learner.learn(data=data, annotations=annotations)
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/dcase_framework/learners.py", line 1032, in learn
    self._setup_keras()
  File "/Users/JL/Documents/SMC10/Master-Thesis/Reference-code/DCASE2017-baseline-system/dcase_framework/learners.py", line 528, in _setup_keras
    blas_libraries = numpy.__config__.blas_opt_info['libraries']
KeyError: 'libraries'
```

I have found a [similar issuse](https://github.com/qutip/qutip/issues/552). In it, the developer, said it was because numpy is using `OSX accelerate BLAS`, which misses the libraries key in the dict.

This is the output of `numpy.show_config()`:
```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
```

**Comment by thisisjl** [comment]
If I set `blas_libraries = []` always, I can run it and train anyway.

**Comment by toni-heittola** [comment]
Thanks for spotting this. Made BLAS library information fetching a bit more robust in commit 97bd78a50699f8d625ecdfd6c98784e6a71a5d0b.
